using CarRentalApi.Domain.Entities;
using Microsoft.EntityFrameworkCore;
namespace CarRentalApi.Data.Database;

public sealed class CarRentalDbContext(
   DbContextOptions<CarRentalDbContext> options
) : DbContext(options) {

   public DbSet<Car> Cars => Set<Car>();
   public DbSet<Reservation> Reservations => Set<Reservation>();


   protected override void OnModelCreating(ModelBuilder modelBuilder) {
      
      base.OnModelCreating(modelBuilder);

      modelBuilder.Entity<Reservation>(b => {
         // TABLE
         b.ToTable("Reservations");
         // primary key
         b.HasKey(r => r.Id);
         b.Property(r => r.Id)
            .ValueGeneratedNever(); // Guid is generated by Domain, no from DB
         
         // scalar properties 
         b.Property(r => r.CarCategory)
            .IsRequired();
         b.Property(r => r.CustomerId)
            .IsRequired();
         b.Property(r => r.CreatedAt)
            .IsRequired();
         b.Property(r => r.Status)
            .IsRequired()
            .HasConversion<string>(); 

         // value object (owned type)
         // Owned: RentalPeriod -> two columns in Reservation table
         b.OwnsOne(r => r.Period, rp => {
            rp.Property(p => p.Start)
               .HasColumnName("Start")
               .HasPrecision(0); // no fractional seconds
            rp.Property(p => p.End)
               .HasColumnName("End")
               .HasPrecision(0); // no fractional seconds
         });

         // Optional aber oft sinnvoll (damit EF das Owned immer erwartet)
         b.Navigation(r => r.Period).IsRequired();
         
         // optinale: indices
         b.HasIndex(x => x.CarCategory);
         b.HasIndex(x => x.CustomerId);
         b.HasIndex(x => x.Status);
      });
   }
}