using CarRentalApi.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace CarRentalApi.Data.Database;

public sealed class ConfigReservations(
   DateTimeOffsetToUnixTimeConverter _dtOffMillis
) : IEntityTypeConfiguration<Reservation> {
   public void Configure(EntityTypeBuilder<Reservation> b) {
      // TABLE
      b.ToTable("Reservations");
      // primary key
      b.HasKey(x => x.Id); // x: Reservation
      b.Property(x => x.Id)
         .ValueGeneratedNever(); // Guid is generated by Domain, no from DB
      // scalar properties 
      b.Property(x => x.CarCategory)
         .IsRequired();
      b.Property(x => x.CustomerId)
         .IsRequired();
      b.Property(x => x.CreatedAt)
         .IsRequired()
         .HasConversion(_dtOffMillis);
      b.Property(x => x.ConfirmedAt)
         .HasConversion(_dtOffMillis);
      b.Property(x => x.CancelledAt)
         .HasConversion(_dtOffMillis);
      b.Property(x => x.ExpiredAt)
         .HasConversion(_dtOffMillis);
      b.Property(x => x.Status)
         .IsRequired()
         .HasConversion<string>();

      // value object (owned type)
      // Owned: RentalPeriod -> two columns in Reservation table
      b.OwnsOne(r => r.Period, rp => {
         rp.Property(p => p.Start)
            .HasColumnName("Start")
            .HasConversion(_dtOffMillis);
         rp.Property(p => p.End)
            .HasColumnName("End")
            .HasConversion(_dtOffMillis); // no fractional seconds
      });

      // Optional aber oft sinnvoll (damit EF das Owned immer erwartet)
      b.Navigation(x => x.Period).IsRequired();

      // optinale: indices
      b.HasIndex(x => x.CarCategory);
      b.HasIndex(x => x.CustomerId);
      b.HasIndex(x => x.Status);
   }
}